## Network Speed

---

- name: run iperf server on bastion
  hosts: bastion
  tasks: 
  - name: set up server 
    shell: iperf3 -s -D -1
    register: bast

  - debug:
      var: bast.stdout

- name: run iperf client on master node
  hosts: master[0]
  gather_facts: false
  
  roles:
   - akirak.coreos-python
  
  vars: 
    bast_ip: "{{ hostvars[groups['bastion'][0]]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}"
  tasks:
  - debug:
      var: bast_ip

  - name: set up client
    shell: iperf3 -c {{ bast_ip }} 
    register: mast

  - debug:
      var: mast.stdout



