## Checking Clocksync Setting
---
- hosts: all

  become: yes

#  roles:
#    - akirak.coreos-python

  tasks:
  - name: Check closksync
    shell: chronyc tracking
    register: output
    failed_when: "output.rc != 0"
