## Checking Kernel Virtual Memory

---
- hosts: all
  gather_facts: false

#  roles:
#    - akirak.coreos-python

  tasks:
  - name: Populate Variable
    shell: sysctl vm.max_map_count|cut -d'=' -f 2
    register: vm

  - debug:
      var: vm.stdout

  - name: Check Kernel VM
    shell: echo "{{ vm.stdout }}"
    register: output
    failed_when: output.stdout|int < 262144
