## Checking Message Limit on Compute Node

---
- hosts: all
  gather_facts: false

  # roles:
  #   - akirak.coreos-python

  tasks:
  - name: Populate msg_max Variable
    shell: sysctl kernel.msgmax|cut -d'=' -f 2
    register: msg_max

  - debug:
      var: msg_max.stdout

  - name: Check Maximum Message Size
    shell: echo "{{ msg_max.stdout }}"
    register: output
    failed_when: output.stdout|int < 65536
